{
    'name': 'Academy Core',
    'version': '19.0.1.0.0',
    'summary': 'Core models and security for the Tennis Academy domain',
    'description': 'Provides core data models, security groups, and base flows for the tennis academy.',
    'author': 'dedepene',
    'website': 'https://example.com',
    'category': 'Education',
    'depends': ['base', 'contacts', 'portal'],
    'data': [
        'security/academy_security.xml',
        'security/ir.model.access.csv',
        'data/academy_sequences.xml',
        'views/academy_skill_group_views.xml',
        'views/academy_player_views.xml',
        'views/res_partner_views.xml',
        'views/player_elevation_wizard_views.xml',
        'views/academy_menu_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
} # type: ignore to suppress linting errors
