{
    'name': 'Academy Billing',
    'version': '19.0.1.0.0',
    'summary': 'Pre-paid billing, templates, and credit reconciliation for the academy',
    'description': 'Implements monthly pre-paid billing, billing templates, ad-hoc charges, and absence credit reconciliation.',
    'author': 'dedepene',
    'website': 'https://example.com',
    'category': 'Education',
    'depends': ['academy_schedule', 'account', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/academy_billing_template_data.xml',
        'data/attendance_billing_cron.xml',
        'data/academy_billing_cron.xml',
        'views/academy_billing_template_views.xml',
        'views/academy_billing_session_template_views.xml',
        'views/attendance_views.xml',
        'views/academy_billing_item_views.xml',
        'views/academy_billing_menu_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
} # type: ignore
